/*
 * LowBit -- 0032_grid_b01_always_taken__c32_hilbert_curve_traversal.c
 * Branch: always_taken | Cache: hilbert_curve_traversal
 * Generated by lowbit_corpus_extend.py. Do not hand-edit;
 * change the catalogue in that script and regenerate instead.
 */

#include "lowbit_runtime.h"

#ifndef SIZE
#define SIZE 8388608u
#endif
#ifndef N
#define N 8000000u
#endif
#define SEED0 0x9E3779B9u


int main(void) {
    uint32_t *buf = (uint32_t *)lowbit_aligned_alloc(sizeof(uint32_t) * SIZE);
    if (!buf) { fprintf(stderr, "alloc failure\n"); return 1; }
    {
        uint32_t iseed_ = SEED0;
        for (uint32_t k_ = 0u; k_ < SIZE; k_++) buf[k_] = lcg_next(&iseed_);
    }

    uint32_t bseed_local = SEED0 ^ 0xC0FFEEu;
    uint32_t *bseed = &bseed_local;
    int prev_taken_local = 0;
    int *prev_taken = &prev_taken_local;

        uint32_t mrows32_ = 1u; uint32_t mcols32_ = SIZE;
        for (uint32_t d_ = 2u; d_ * d_ <= SIZE; d_++) { if (SIZE % d_ == 0u) mrows32_ = d_; }
        mcols32_ = SIZE / (mrows32_ == 0u ? 1u : mrows32_);
        if (mrows32_ == 0u) mrows32_ = 1u;
        uint32_t bound32_ = 1u;
        while (bound32_ < mrows32_ || bound32_ < mcols32_) bound32_ <<= 1u;

    /* ---- warm-up (untimed): primes caches / predictor / pattern state
     * with the exact same access pattern before measurement begins ---- */
    uint64_t warmup_n = N / 10u;
    if (warmup_n > 200000u) warmup_n = 200000u;
    volatile uint64_t warmup_sink = 0;
    for (uint64_t i = 0; i < warmup_n; i++) {
        uint32_t idx = ({ uint32_t d32_ = (uint32_t)(i % ((uint32_t)bound32_ * (uint32_t)bound32_));
     uint32_t t32_ = d32_, x32_ = 0u, y32_ = 0u;
     for (uint32_t s32_ = 1u; s32_ < bound32_; s32_ <<= 1u) {
       uint32_t rx32_ = 1u & (t32_ / 2u);
       uint32_t ry32_ = 1u & (t32_ ^ rx32_);
       if (ry32_ == 0u) {
         if (rx32_ == 1u) { x32_ = s32_ - 1u - x32_; y32_ = s32_ - 1u - y32_; }
         { uint32_t tmp32_ = x32_; x32_ = y32_; y32_ = tmp32_; }
       }
       x32_ += s32_ * rx32_; y32_ += s32_ * ry32_;
       t32_ /= 4u;
     }
     (x32_ < mrows32_ && y32_ < mcols32_) ? (uint32_t)(x32_ * mcols32_ + y32_) : (uint32_t)(i % SIZE); });
        uint32_t v = buf[idx];
        int taken;
        taken = 1;
        if (taken) { warmup_sink += v; } else { warmup_sink -= (v >> 1); }
        buf[idx] = v + 1u;
    }

    /* ---- region of interest (timed): this is what gets reported ---- */
    volatile uint64_t sink = 0;
    uint64_t taken_count = 0, nottaken_count = 0;

    lowbit_timer_t timer;
    lowbit_roi_start(&timer);

    for (uint64_t i = 0; i < N; i++) {
        uint32_t idx = ({ uint32_t d32_ = (uint32_t)(i % ((uint32_t)bound32_ * (uint32_t)bound32_));
     uint32_t t32_ = d32_, x32_ = 0u, y32_ = 0u;
     for (uint32_t s32_ = 1u; s32_ < bound32_; s32_ <<= 1u) {
       uint32_t rx32_ = 1u & (t32_ / 2u);
       uint32_t ry32_ = 1u & (t32_ ^ rx32_);
       if (ry32_ == 0u) {
         if (rx32_ == 1u) { x32_ = s32_ - 1u - x32_; y32_ = s32_ - 1u - y32_; }
         { uint32_t tmp32_ = x32_; x32_ = y32_; y32_ = tmp32_; }
       }
       x32_ += s32_ * rx32_; y32_ += s32_ * ry32_;
       t32_ /= 4u;
     }
     (x32_ < mrows32_ && y32_ < mcols32_) ? (uint32_t)(x32_ * mcols32_ + y32_) : (uint32_t)(i % SIZE); });
        uint32_t v = buf[idx];
        int taken;
        taken = 1;
        if (taken) {
            sink += v;
            taken_count++;
        } else {
            sink -= (v >> 1);
            nottaken_count++;
        }
        buf[idx] = v + 1u;
    }

    lowbit_roi_stop(&timer);

    

    int validation_pass = ((taken_count + nottaken_count) == N) ? 1 : 0;

    printf("program=0032_grid_b01_always_taken__c32_hilbert_curve_traversal.c\n");
    printf("branch_pattern=always_taken\n");
    printf("cache_pattern=hilbert_curve_traversal\n");
    printf("predictor_stress_type=static/trivial\n");
    printf("expected_dominant_miss_type=mixed spatial (traversal-order dependent)\n");
    printf("size_tier=xlarge_DRAM\n");
    printf("backend=%s\n", LOWBIT_BACKEND);
    printf("compiler=%s\n", lowbit_compiler_version());
    printf("arch=%s\n", lowbit_arch_name());
    printf("SIZE=%u N=%u SEED=%u\n", (unsigned)SIZE, (unsigned)N, (unsigned)SEED0);
    printf("warmup_iterations=%llu\n", (unsigned long long)warmup_n);
    printf("taken=%llu nottaken=%llu\n",
           (unsigned long long)taken_count, (unsigned long long)nottaken_count);
    printf("sink=%llu\n", (unsigned long long)sink);
    printf("validation=%s\n", validation_pass ? "PASS" : "FAIL");
    printf("roi_elapsed_seconds=%.9f\n", lowbit_roi_seconds(&timer));

    /* Explicit fflush + _Exit (not return/exit): modern statically-
     * linked glibc's normal exit() path does pthread-related futex
     * cleanup that some emulators' syscall-emulation modes (notably
     * gem5 SE mode) cannot resolve, causing the process to hang
     * indefinitely at 100% CPU after main() has already finished and
     * printed all its output. _Exit() skips that cleanup path
     * entirely and goes straight to the exit syscall; fflush(stdout)
     * first guarantees the printf output above isn't lost, since
     * _Exit() does NOT flush stdio buffers on its own (this matters
     * because stdout is fully buffered, not line-buffered, whenever
     * it's redirected to a file -- exactly how every run script here
     * captures it). */
    fflush(stdout);
    _Exit(validation_pass ? 0 : 2);
}
