/*
 * LowBit -- 1519_grid_b31_prime_period13__c19_matrix_diagonal_wavefront.c
 * Branch: prime_period13 | Cache: matrix_diagonal_wavefront
 * Generated by lowbit_corpus_extend.py. Do not hand-edit;
 * change the catalogue in that script and regenerate instead.
 */

#include "lowbit_runtime.h"

#ifndef SIZE
#define SIZE 4096u
#endif
#ifndef N
#define N 1000000u
#endif
#define SEED0 0x9E3779B9u


int main(void) {
    uint32_t *buf = (uint32_t *)lowbit_aligned_alloc(sizeof(uint32_t) * SIZE);
    if (!buf) { fprintf(stderr, "alloc failure\n"); return 1; }
    {
        uint32_t iseed_ = SEED0;
        for (uint32_t k_ = 0u; k_ < SIZE; k_++) buf[k_] = lcg_next(&iseed_);
    }

    uint32_t bseed_local = SEED0 ^ 0xC0FFEEu;
    uint32_t *bseed = &bseed_local;
    int prev_taken_local = 0;
    int *prev_taken = &prev_taken_local;

        uint32_t mrows19_ = 1u; uint32_t mcols19_ = SIZE;
        for (uint32_t d_ = 2u; d_ * d_ <= SIZE; d_++) { if (SIZE % d_ == 0u) mrows19_ = d_; }
        mcols19_ = SIZE / (mrows19_ == 0u ? 1u : mrows19_);
        if (mrows19_ == 0u) mrows19_ = 1u;
        uint32_t ndiag19_ = mrows19_ + mcols19_ - 1u;

    /* ---- warm-up (untimed): primes caches / predictor / pattern state
     * with the exact same access pattern before measurement begins ---- */
    uint64_t warmup_n = N / 10u;
    if (warmup_n > 200000u) warmup_n = 200000u;
    volatile uint64_t warmup_sink = 0;
    for (uint64_t i = 0; i < warmup_n; i++) {
        uint32_t idx = ({ uint32_t diag_ = (uint32_t)((i / (mrows19_ < mcols19_ ? mrows19_ : mcols19_)) % ndiag19_);
     uint32_t within_ = (uint32_t)(i % (mrows19_ < mcols19_ ? mrows19_ : mcols19_));
     uint32_t r_ = (diag_ < mrows19_) ? (diag_ - (within_ % (diag_ + 1u))) : (mrows19_ - 1u - within_ % mrows19_);
     uint32_t c_ = diag_ - r_;
     (r_ < mrows19_ && c_ < mcols19_) ? (r_ * mcols19_ + c_) : (uint32_t)(i % SIZE); });
        uint32_t v = buf[idx];
        int taken;
        taken = (i % 13u) < 7u;
        if (taken) { warmup_sink += v; } else { warmup_sink -= (v >> 1); }
        buf[idx] = v + 1u;
    }

    /* ---- region of interest (timed): this is what gets reported ---- */
    volatile uint64_t sink = 0;
    uint64_t taken_count = 0, nottaken_count = 0;

    lowbit_timer_t timer;
    lowbit_roi_start(&timer);

    for (uint64_t i = 0; i < N; i++) {
        uint32_t idx = ({ uint32_t diag_ = (uint32_t)((i / (mrows19_ < mcols19_ ? mrows19_ : mcols19_)) % ndiag19_);
     uint32_t within_ = (uint32_t)(i % (mrows19_ < mcols19_ ? mrows19_ : mcols19_));
     uint32_t r_ = (diag_ < mrows19_) ? (diag_ - (within_ % (diag_ + 1u))) : (mrows19_ - 1u - within_ % mrows19_);
     uint32_t c_ = diag_ - r_;
     (r_ < mrows19_ && c_ < mcols19_) ? (r_ * mcols19_ + c_) : (uint32_t)(i % SIZE); });
        uint32_t v = buf[idx];
        int taken;
        taken = (i % 13u) < 7u;
        if (taken) {
            sink += v;
            taken_count++;
        } else {
            sink -= (v >> 1);
            nottaken_count++;
        }
        buf[idx] = v + 1u;
    }

    lowbit_roi_stop(&timer);

    

    int validation_pass = ((taken_count + nottaken_count) == N) ? 1 : 0;

    printf("program=1519_grid_b31_prime_period13__c19_matrix_diagonal_wavefront.c\n");
    printf("branch_pattern=prime_period13\n");
    printf("cache_pattern=matrix_diagonal_wavefront\n");
    printf("predictor_stress_type=static/periodic\n");
    printf("expected_dominant_miss_type=mixed spatial (traversal-order dependent)\n");
    printf("size_tier=small_L1\n");
    printf("backend=%s\n", LOWBIT_BACKEND);
    printf("compiler=%s\n", lowbit_compiler_version());
    printf("arch=%s\n", lowbit_arch_name());
    printf("SIZE=%u N=%u SEED=%u\n", (unsigned)SIZE, (unsigned)N, (unsigned)SEED0);
    printf("warmup_iterations=%llu\n", (unsigned long long)warmup_n);
    printf("taken=%llu nottaken=%llu\n",
           (unsigned long long)taken_count, (unsigned long long)nottaken_count);
    printf("sink=%llu\n", (unsigned long long)sink);
    printf("validation=%s\n", validation_pass ? "PASS" : "FAIL");
    printf("roi_elapsed_seconds=%.9f\n", lowbit_roi_seconds(&timer));

    /* Explicit fflush + _Exit (not return/exit): modern statically-
     * linked glibc's normal exit() path does pthread-related futex
     * cleanup that some emulators' syscall-emulation modes (notably
     * gem5 SE mode) cannot resolve, causing the process to hang
     * indefinitely at 100% CPU after main() has already finished and
     * printed all its output. _Exit() skips that cleanup path
     * entirely and goes straight to the exit syscall; fflush(stdout)
     * first guarantees the printf output above isn't lost, since
     * _Exit() does NOT flush stdio buffers on its own (this matters
     * because stdout is fully buffered, not line-buffered, whenever
     * it's redirected to a file -- exactly how every run script here
     * captures it). */
    fflush(stdout);
    _Exit(validation_pass ? 0 : 2);
}
