/*
 * LowBit -- 2300_grid_b46_lookup_table_driven__c50_streaming_with_periodic_flush.c
 * Branch: lookup_table_driven | Cache: streaming_with_periodic_flush
 * Generated by lowbit_corpus_extend.py. Do not hand-edit;
 * change the catalogue in that script and regenerate instead.
 */

#include "lowbit_runtime.h"

#ifndef SIZE
#define SIZE 1048576u
#endif
#ifndef N
#define N 5000000u
#endif
#define SEED0 0x9E3779B9u


int main(void) {
    uint32_t *buf = (uint32_t *)lowbit_aligned_alloc(sizeof(uint32_t) * SIZE);
    if (!buf) { fprintf(stderr, "alloc failure\n"); return 1; }
    {
        uint32_t iseed_ = SEED0;
        for (uint32_t k_ = 0u; k_ < SIZE; k_++) buf[k_] = lcg_next(&iseed_);
    }

    uint32_t bseed_local = SEED0 ^ 0xC0FFEEu;
    uint32_t *bseed = &bseed_local;
    int prev_taken_local = 0;
    int *prev_taken = &prev_taken_local;

        const uint64_t FLUSH_PERIOD50_ = 10000u;

    /* ---- warm-up (untimed): primes caches / predictor / pattern state
     * with the exact same access pattern before measurement begins ---- */
    uint64_t warmup_n = N / 10u;
    if (warmup_n > 200000u) warmup_n = 200000u;
    volatile uint64_t warmup_sink = 0;
    for (uint64_t i = 0; i < warmup_n; i++) {
        uint32_t idx = (uint32_t)(((i % FLUSH_PERIOD50_) == 0u) ? 0u : (i % SIZE));
        uint32_t v = buf[idx];
        int taken;
        { static unsigned char tbl46_[256]; static int init46_ = 0;
  if (!init46_) {
    uint32_t ts46_ = 0x46464646u;
    for (int k46_ = 0; k46_ < 256; k46_++) { tbl46_[k46_] = (unsigned char)((lcg_next(&ts46_) >> 16) & 1u); }
    init46_ = 1;
  }
  taken = tbl46_[v & 0xFFu]; }
        if (taken) { warmup_sink += v; } else { warmup_sink -= (v >> 1); }
        buf[idx] = v + 1u;
    }

    /* ---- region of interest (timed): this is what gets reported ---- */
    volatile uint64_t sink = 0;
    uint64_t taken_count = 0, nottaken_count = 0;

    lowbit_timer_t timer;
    lowbit_roi_start(&timer);

    for (uint64_t i = 0; i < N; i++) {
        uint32_t idx = (uint32_t)(((i % FLUSH_PERIOD50_) == 0u) ? 0u : (i % SIZE));
        uint32_t v = buf[idx];
        int taken;
        { static unsigned char tbl46_[256]; static int init46_ = 0;
  if (!init46_) {
    uint32_t ts46_ = 0x46464646u;
    for (int k46_ = 0; k46_ < 256; k46_++) { tbl46_[k46_] = (unsigned char)((lcg_next(&ts46_) >> 16) & 1u); }
    init46_ = 1;
  }
  taken = tbl46_[v & 0xFFu]; }
        if (taken) {
            sink += v;
            taken_count++;
        } else {
            sink -= (v >> 1);
            nottaken_count++;
        }
        buf[idx] = v + 1u;
    }

    lowbit_roi_stop(&timer);

    

    int validation_pass = ((taken_count + nottaken_count) == N) ? 1 : 0;

    printf("program=2300_grid_b46_lookup_table_driven__c50_streaming_with_periodic_flush.c\n");
    printf("branch_pattern=lookup_table_driven\n");
    printf("cache_pattern=streaming_with_periodic_flush\n");
    printf("predictor_stress_type=stochastic\n");
    printf("expected_dominant_miss_type=compulsory+streaming (prefetch-friendly)\n");
    printf("size_tier=large_L3\n");
    printf("backend=%s\n", LOWBIT_BACKEND);
    printf("compiler=%s\n", lowbit_compiler_version());
    printf("arch=%s\n", lowbit_arch_name());
    printf("SIZE=%u N=%u SEED=%u\n", (unsigned)SIZE, (unsigned)N, (unsigned)SEED0);
    printf("warmup_iterations=%llu\n", (unsigned long long)warmup_n);
    printf("taken=%llu nottaken=%llu\n",
           (unsigned long long)taken_count, (unsigned long long)nottaken_count);
    printf("sink=%llu\n", (unsigned long long)sink);
    printf("validation=%s\n", validation_pass ? "PASS" : "FAIL");
    printf("roi_elapsed_seconds=%.9f\n", lowbit_roi_seconds(&timer));

    /* Explicit fflush + _Exit (not return/exit): modern statically-
     * linked glibc's normal exit() path does pthread-related futex
     * cleanup that some emulators' syscall-emulation modes (notably
     * gem5 SE mode) cannot resolve, causing the process to hang
     * indefinitely at 100% CPU after main() has already finished and
     * printed all its output. _Exit() skips that cleanup path
     * entirely and goes straight to the exit syscall; fflush(stdout)
     * first guarantees the printf output above isn't lost, since
     * _Exit() does NOT flush stdio buffers on its own (this matters
     * because stdout is fully buffered, not line-buffered, whenever
     * it's redirected to a file -- exactly how every run script here
     * captures it). */
    fflush(stdout);
    _Exit(validation_pass ? 0 : 2);
}
