/*
 * LowBit -- 2349_grid_b47_mutual_ping_pong_recursion__c49_binary_heap_parent_child.c
 * Branch: mutual_ping_pong_recursion | Cache: binary_heap_parent_child
 * Generated by lowbit_corpus_extend.py. Do not hand-edit;
 * change the catalogue in that script and regenerate instead.
 */

#include "lowbit_runtime.h"

#ifndef SIZE
#define SIZE 1048576u
#endif
#ifndef N
#define N 5000000u
#endif
#define SEED0 0x9E3779B9u


static uint32_t mutB47(uint32_t depth, uint32_t acc);
static uint32_t mutA47(uint32_t depth, uint32_t acc) {
    if (depth == 0u) return acc;
    return mutB47(depth - 1u, acc + depth);
}
static uint32_t mutB47(uint32_t depth, uint32_t acc) {
    if (depth == 0u) return acc;
    return mutA47(depth - 1u, acc ^ depth);
}

int main(void) {
    uint32_t *buf = (uint32_t *)lowbit_aligned_alloc(sizeof(uint32_t) * SIZE);
    if (!buf) { fprintf(stderr, "alloc failure\n"); return 1; }
    {
        uint32_t iseed_ = SEED0;
        for (uint32_t k_ = 0u; k_ < SIZE; k_++) buf[k_] = lcg_next(&iseed_);
    }

    uint32_t bseed_local = SEED0 ^ 0xC0FFEEu;
    uint32_t *bseed = &bseed_local;
    int prev_taken_local = 0;
    int *prev_taken = &prev_taken_local;

        uint32_t heappos49_ = 0u; uint32_t cseed49_ = SEED0 ^ 0x49494949u;

    /* ---- warm-up (untimed): primes caches / predictor / pattern state
     * with the exact same access pattern before measurement begins ---- */
    uint64_t warmup_n = N / 10u;
    if (warmup_n > 200000u) warmup_n = 200000u;
    volatile uint64_t warmup_sink = 0;
    for (uint64_t i = 0; i < warmup_n; i++) {
        uint32_t idx = ({ uint32_t choice49_ = lcg_next(&cseed49_) % 3u; uint32_t next49_;
     if (choice49_ == 0u) next49_ = 2u * heappos49_ + 1u;
     else if (choice49_ == 1u) next49_ = 2u * heappos49_ + 2u;
     else next49_ = (heappos49_ > 0u) ? (heappos49_ - 1u) / 2u : 0u;
     if (next49_ >= SIZE) next49_ = 0u;
     heappos49_ = next49_;
     heappos49_; });
        uint32_t v = buf[idx];
        int taken;
        { uint32_t depth47_ = (v % 10u) + 1u;
  uint32_t r47_ = mutA47(depth47_, v);
  taken = (r47_ & 1u) == 0u; v = r47_; }
        if (taken) { warmup_sink += v; } else { warmup_sink -= (v >> 1); }
        buf[idx] = v + 1u;
    }

    /* ---- region of interest (timed): this is what gets reported ---- */
    volatile uint64_t sink = 0;
    uint64_t taken_count = 0, nottaken_count = 0;

    lowbit_timer_t timer;
    lowbit_roi_start(&timer);

    for (uint64_t i = 0; i < N; i++) {
        uint32_t idx = ({ uint32_t choice49_ = lcg_next(&cseed49_) % 3u; uint32_t next49_;
     if (choice49_ == 0u) next49_ = 2u * heappos49_ + 1u;
     else if (choice49_ == 1u) next49_ = 2u * heappos49_ + 2u;
     else next49_ = (heappos49_ > 0u) ? (heappos49_ - 1u) / 2u : 0u;
     if (next49_ >= SIZE) next49_ = 0u;
     heappos49_ = next49_;
     heappos49_; });
        uint32_t v = buf[idx];
        int taken;
        { uint32_t depth47_ = (v % 10u) + 1u;
  uint32_t r47_ = mutA47(depth47_, v);
  taken = (r47_ & 1u) == 0u; v = r47_; }
        if (taken) {
            sink += v;
            taken_count++;
        } else {
            sink -= (v >> 1);
            nottaken_count++;
        }
        buf[idx] = v + 1u;
    }

    lowbit_roi_stop(&timer);

    

    int validation_pass = ((taken_count + nottaken_count) == N) ? 1 : 0;

    printf("program=2349_grid_b47_mutual_ping_pong_recursion__c49_binary_heap_parent_child.c\n");
    printf("branch_pattern=mutual_ping_pong_recursion\n");
    printf("cache_pattern=binary_heap_parent_child\n");
    printf("predictor_stress_type=control-flow/call-return\n");
    printf("expected_dominant_miss_type=capacity (uniform random)\n");
    printf("size_tier=large_L3\n");
    printf("backend=%s\n", LOWBIT_BACKEND);
    printf("compiler=%s\n", lowbit_compiler_version());
    printf("arch=%s\n", lowbit_arch_name());
    printf("SIZE=%u N=%u SEED=%u\n", (unsigned)SIZE, (unsigned)N, (unsigned)SEED0);
    printf("warmup_iterations=%llu\n", (unsigned long long)warmup_n);
    printf("taken=%llu nottaken=%llu\n",
           (unsigned long long)taken_count, (unsigned long long)nottaken_count);
    printf("sink=%llu\n", (unsigned long long)sink);
    printf("validation=%s\n", validation_pass ? "PASS" : "FAIL");
    printf("roi_elapsed_seconds=%.9f\n", lowbit_roi_seconds(&timer));

    /* Explicit fflush + _Exit (not return/exit): modern statically-
     * linked glibc's normal exit() path does pthread-related futex
     * cleanup that some emulators' syscall-emulation modes (notably
     * gem5 SE mode) cannot resolve, causing the process to hang
     * indefinitely at 100% CPU after main() has already finished and
     * printed all its output. _Exit() skips that cleanup path
     * entirely and goes straight to the exit syscall; fflush(stdout)
     * first guarantees the printf output above isn't lost, since
     * _Exit() does NOT flush stdio buffers on its own (this matters
     * because stdout is fully buffered, not line-buffered, whenever
     * it's redirected to a file -- exactly how every run script here
     * captures it). */
    fflush(stdout);
    _Exit(validation_pass ? 0 : 2);
}
